name: remote ssh command
on: [workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PRIVATE_KEY }}
        script: whoami